apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: hello-node-topic
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: hello-node-function
spec:
  protocol: http
  input: hello-node-topic
  container:
    image: projectriff/hello-node:0.0.1
